"""Text-only socials. No world templates or saved area data are involved."""

# First-person and third-person verb phrases, with final punctuation included.
EMOTES = {
    "yawn": ("yawn.", "yawns."),
    "smile": ("smile warmly.", "smiles warmly."),
    "grin": ("grin from ear to ear.", "grins from ear to ear."),
    "laugh": ("laugh out loud.", "laughs out loud."),
    "chuckle": ("chuckle quietly.", "chuckles quietly."),
    "giggle": ("giggle.", "giggles."),
    "snicker": ("snicker mischievously.", "snickers mischievously."),
    "smirk": ("smirk.", "smirks."),
    "wink": ("wink playfully.", "winks playfully."),
    "blush": ("blush.", "blushes."),
    "beam": ("beam with delight.", "beams with delight."),
    "cheer": ("cheer enthusiastically!", "cheers enthusiastically!"),
    "clap": ("clap your hands.", "claps their hands."),
    "applaud": ("break into applause.", "breaks into applause."),
    "dance": ("do a little dance.", "does a little dance."),
    "celebrate": ("raise your arms in celebration!", "raises their arms in celebration!"),
    "wave": ("wave hello.", "waves hello."),
    "bye": ("wave goodbye.", "waves goodbye."),
    "bow": ("bow respectfully.", "bows respectfully."),
    "salute": ("offer a crisp salute.", "offers a crisp salute."),
    "nod": ("nod in agreement.", "nods in agreement."),
    "shakehead": ("shake your head.", "shakes their head."),
    "shrug": ("shrug your shoulders.", "shrugs their shoulders."),
    "thumbsup": ("give a thumbs-up.", "gives a thumbs-up."),
    "thumbsdown": ("give a thumbs-down.", "gives a thumbs-down."),
    "thanks": ("offer your thanks.", "offers their thanks."),
    "sorry": ("offer a sincere apology.", "offers a sincere apology."),
    "welcome": ("offer a friendly greeting.", "offers a friendly greeting."),
    "sigh": ("let out a long sigh.", "lets out a long sigh."),
    "groan": ("groan in dismay.", "groans in dismay."),
    "grumble": ("grumble under your breath.", "grumbles under their breath."),
    "frown": ("frown.", "frowns."),
    "pout": ("pout.", "pouts."),
    "sulk": ("sulk quietly.", "sulks quietly."),
    "cry": ("shed a tear.", "sheds a tear."),
    "sob": ("sob softly.", "sobs softly."),
    "sniffle": ("sniffle.", "sniffles."),
    "facepalm": ("bury your face in your palm.", "buries their face in their palm."),
    "eyeroll": ("roll your eyes.", "rolls their eyes."),
    "glare": ("glare fiercely.", "glares fiercely."),
    "scowl": ("scowl.", "scowls."),
    "huff": ("huff indignantly.", "huffs indignantly."),
    "gasp": ("gasp in surprise!", "gasps in surprise!"),
    "blink": ("blink in surprise.", "blinks in surprise."),
    "stare": ("stare in disbelief.", "stares in disbelief."),
    "squint": ("squint thoughtfully.", "squints thoughtfully."),
    "ponder": ("ponder the situation.", "ponders the situation."),
    "think": ("rub your chin thoughtfully.", "rubs their chin thoughtfully."),
    "hmm": ("hum thoughtfully.", "hums thoughtfully."),
    "confused": ("look puzzled.", "looks puzzled."),
    "doubt": ("raise a skeptical eyebrow.", "raises a skeptical eyebrow."),
    "curious": ("tilt your head curiously.", "tilts their head curiously."),
    "nervous": ("fidget nervously.", "fidgets nervously."),
    "gulp": ("gulp nervously.", "gulps nervously."),
    "shiver": ("shiver.", "shivers."),
    "tremble": ("tremble slightly.", "trembles slightly."),
    "wince": ("wince.", "winces."),
    "cringe": ("cringe awkwardly.", "cringes awkwardly."),
    "relief": ("breathe a sigh of relief.", "breathes a sigh of relief."),
    "stretch": ("stretch your arms.", "stretches their arms."),
    "cough": ("cough politely.", "coughs politely."),
    "sneeze": ("sneeze!", "sneezes!"),
    "hiccup": ("hiccup.", "hiccups."),
    "whistle": ("whistle a cheerful tune.", "whistles a cheerful tune."),
    "hum": ("hum a quiet melody.", "hums a quiet melody."),
    "sing": ("sing a few cheerful notes.", "sings a few cheerful notes."),
    "tap": ("tap your foot impatiently.", "taps their foot impatiently."),
    "fidget": ("fidget restlessly.", "fidgets restlessly."),
    "crackknuckles": ("crack your knuckles.", "cracks their knuckles."),
    "flex": ("flex your muscles.", "flexes their muscles."),
    "peace": ("flash a peace sign.", "flashes a peace sign."),
    "heart": ("make a heart shape with your hands.", "makes a heart shape with their hands."),
    "headband": ("adjust your headband.", "adjusts their headband."),
    "handsigns": ("practice a sequence of hand signs.", "practices a sequence of hand signs."),
    "determined": ("clench your fist with determination.", "clenches their fist with determination."),
    "challenge": ("settle into a challenging pose.", "settles into a challenging pose."),
    "focus": ("take a slow, steadying breath.", "takes a slow, steadying breath."),
    "ramen": ("daydream about a steaming bowl of ramen.", "daydreams about a steaming bowl of ramen."),
    "sweatdrop": ("wear an awkward, embarrassed smile.", "wears an awkward, embarrassed smile."),
    "victory": ("strike a triumphant pose!", "strikes a triumphant pose!"),
}


def list_text() -> str:
    names = sorted(EMOTES)
    lines = ["&WText emotes&x", "@yawn: current room | ooc @yawn: global OOC",
             "Use one emote name with no extra words. These are cosmetic only.", ""]
    for offset in range(0, len(names), 4):
        lines.append("  " + "".join(("@" + name).ljust(19) for name in names[offset:offset + 4]).rstrip())
    lines.append(f"\n{len(names)} emotes available.")
    return "\n".join(lines)
